/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postes1;

/**
 *
 * @author user
 */
public class Suhu extends javax.swing.JFrame {

    /**
     * Creates new form Suhu
     */
    public Suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Celcius = new javax.swing.JLabel();
        TCel = new javax.swing.JTextField();
        BCel = new javax.swing.JButton();
        HCel = new javax.swing.JButton();
        cfah = new javax.swing.JLabel();
        TFah = new javax.swing.JTextField();
        cRea = new javax.swing.JLabel();
        TRea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TKel = new javax.swing.JTextField();
        Fahrenheit = new javax.swing.JLabel();
        TFah2 = new javax.swing.JTextField();
        BFah = new javax.swing.JButton();
        HFah = new javax.swing.JButton();
        fCel = new javax.swing.JLabel();
        fRea = new javax.swing.JLabel();
        fKel = new javax.swing.JLabel();
        TCel2 = new javax.swing.JTextField();
        TRea2 = new javax.swing.JTextField();
        TKel2 = new javax.swing.JTextField();
        reamur = new javax.swing.JLabel();
        TRea3 = new javax.swing.JTextField();
        BRea = new javax.swing.JButton();
        HRea = new javax.swing.JButton();
        rCel = new javax.swing.JLabel();
        TCel3 = new javax.swing.JTextField();
        rFah = new javax.swing.JLabel();
        TFah3 = new javax.swing.JTextField();
        rKel = new javax.swing.JLabel();
        TKel3 = new javax.swing.JTextField();
        Kelvin = new javax.swing.JLabel();
        TKel4 = new javax.swing.JTextField();
        BKel = new javax.swing.JButton();
        HKel = new javax.swing.JButton();
        kCel = new javax.swing.JLabel();
        TCel4 = new javax.swing.JTextField();
        kFah = new javax.swing.JLabel();
        TFah4 = new javax.swing.JTextField();
        kRea = new javax.swing.JLabel();
        TRea4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("KONVERSI SUHU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        Celcius.setText("Celcius :");

        BCel.setText("Konversi");
        BCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCelActionPerformed(evt);
            }
        });

        HCel.setText("Delete");
        HCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCelActionPerformed(evt);
            }
        });

        cfah.setText("Fah");

        cRea.setText("Rea");

        jLabel5.setText("Kel");

        Fahrenheit.setText("Fahrenheit");

        BFah.setText("Konversi");
        BFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFahActionPerformed(evt);
            }
        });

        HFah.setText("Delete");
        HFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HFahActionPerformed(evt);
            }
        });

        fCel.setText("Cel");

        fRea.setText("Rea");

        fKel.setText("Kel");

        reamur.setText("Reamur");

        BRea.setText("Konversi");
        BRea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReaActionPerformed(evt);
            }
        });

        HRea.setText("Delete");
        HRea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HReaActionPerformed(evt);
            }
        });

        rCel.setText("Cel");

        TCel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCel3ActionPerformed(evt);
            }
        });

        rFah.setText("Fah");

        TFah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFah3ActionPerformed(evt);
            }
        });

        rKel.setText("Kel");

        TKel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKel3ActionPerformed(evt);
            }
        });

        Kelvin.setText("Kelvin");

        BKel.setText("Konversi");
        BKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKelActionPerformed(evt);
            }
        });

        HKel.setText("Delete");
        HKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HKelActionPerformed(evt);
            }
        });

        kCel.setText("Cel");

        TCel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCel4ActionPerformed(evt);
            }
        });

        kFah.setText("Fah");

        kRea.setText("Rea");

        jButton1.setText("Kalkulator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BFah)
                    .addComponent(HFah))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rKel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TKel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rCel)
                                    .addComponent(rFah))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFah3)
                                    .addComponent(TCel3)))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Celcius)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TCel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cRea)
                                    .addComponent(cfah))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TKel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TRea, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(reamur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TRea3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(HCel))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(BCel)))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Fahrenheit)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fRea)
                                                .addComponent(fCel)
                                                .addComponent(fKel)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(BRea)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kCel)
                                            .addComponent(Kelvin)
                                            .addComponent(kFah))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(kRea)
                                            .addGap(10, 10, 10)))))
                            .addComponent(HRea))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TCel2)
                                    .addComponent(TRea2)
                                    .addComponent(TFah4)
                                    .addComponent(TCel4)
                                    .addComponent(TKel2)
                                    .addComponent(TFah2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TKel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TRea4))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BKel)
                    .addComponent(HKel))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celcius)
                    .addComponent(TCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCel)
                    .addComponent(Fahrenheit)
                    .addComponent(TFah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFah))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cRea)
                            .addComponent(TRea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cfah)
                            .addComponent(TFah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HCel)
                            .addComponent(TCel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HFah)
                            .addComponent(fCel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TRea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fRea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TKel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fKel))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TKel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(reamur)
                                .addComponent(TRea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Kelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BKel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kCel)
                            .addComponent(TCel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HKel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kFah)
                            .addComponent(TFah4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kRea)
                            .addComponent(TRea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TCel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rCel))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BRea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HRea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rFah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TKel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rKel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCelActionPerformed
        int Cel=Integer.parseInt(TCel.getText());
        double fah=(1.8*Cel)+32;
        double rea=(0.8*Cel);
        double kel=(Cel+273);
        
        TFah.setText(String.valueOf(fah));
        TRea.setText(String.valueOf(rea));
        TKel.setText(String.valueOf(kel));
        // TODO add your handling code here:
    }//GEN-LAST:event_BCelActionPerformed

    private void HCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCelActionPerformed
        TCel.setText("");
        TFah.setText("");
        TRea.setText("");
        TKel.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_HCelActionPerformed

    private void HFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HFahActionPerformed
        TFah2.setText("");
        TCel2.setText("");
        TRea2.setText("");
        TKel2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_HFahActionPerformed

    private void BFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFahActionPerformed
     int Fah=Integer.parseInt(TFah2.getText());
        double cel=(Fah-32)/1.8;
        double rea=(Fah-32)/2.25;
        double kel=(Fah+459)/1.8;
        
        TCel2.setText(String.valueOf(cel));
        TRea2.setText(String.valueOf(rea));
        TKel2.setText(String.valueOf(kel));
        // TODO add your handling code here:
    }//GEN-LAST:event_BFahActionPerformed

    private void BReaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReaActionPerformed
      int Rea=Integer.parseInt(TRea3.getText());
        double cel=(Rea/0.8);
        double fah=(Rea*2.25)+491.67;
        double kel=(Rea/0.8)+273.15;  
        
        TCel3.setText(String.valueOf(cel));
        TFah3.setText(String.valueOf(fah));
        TKel3.setText(String.valueOf(kel));
        // TODO add your handling code here:
    }//GEN-LAST:event_BReaActionPerformed

    private void HReaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HReaActionPerformed
        TRea3.setText("");
        TCel3.setText("");
        TFah3.setText("");
        TKel3.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_HReaActionPerformed

    private void BKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKelActionPerformed
        int Kel=Integer.parseInt(TKel4.getText());
        double cel=(Kel-273.15);
        double fah=(Kel-273.15)*0.8;
        double rea=(Kel*1.8)-459.67;
        
        TCel4.setText(String.valueOf(cel));
        TFah4.setText(String.valueOf(fah));
        TRea4.setText(String.valueOf(rea));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BKelActionPerformed

    private void HKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HKelActionPerformed
        TKel4.setText("");
        TCel4.setText("");
        TFah4.setText("");
        TRea4.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_HKelActionPerformed

    private void TCel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCel3ActionPerformed

    private void TFah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFah3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFah3ActionPerformed

    private void TKel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKel3ActionPerformed

    private void TCel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCel4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Kalkulator a = new Kalkulator();
a.setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCel;
    private javax.swing.JButton BFah;
    private javax.swing.JButton BKel;
    private javax.swing.JButton BRea;
    private javax.swing.JLabel Celcius;
    private javax.swing.JLabel Fahrenheit;
    private javax.swing.JButton HCel;
    private javax.swing.JButton HFah;
    private javax.swing.JButton HKel;
    private javax.swing.JButton HRea;
    private javax.swing.JLabel Kelvin;
    private javax.swing.JTextField TCel;
    private javax.swing.JTextField TCel2;
    private javax.swing.JTextField TCel3;
    private javax.swing.JTextField TCel4;
    private javax.swing.JTextField TFah;
    private javax.swing.JTextField TFah2;
    private javax.swing.JTextField TFah3;
    private javax.swing.JTextField TFah4;
    private javax.swing.JTextField TKel;
    private javax.swing.JTextField TKel2;
    private javax.swing.JTextField TKel3;
    private javax.swing.JTextField TKel4;
    private javax.swing.JTextField TRea;
    private javax.swing.JTextField TRea2;
    private javax.swing.JTextField TRea3;
    private javax.swing.JTextField TRea4;
    private javax.swing.JLabel cRea;
    private javax.swing.JLabel cfah;
    private javax.swing.JLabel fCel;
    private javax.swing.JLabel fKel;
    private javax.swing.JLabel fRea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kCel;
    private javax.swing.JLabel kFah;
    private javax.swing.JLabel kRea;
    private javax.swing.JLabel rCel;
    private javax.swing.JLabel rFah;
    private javax.swing.JLabel rKel;
    private javax.swing.JLabel reamur;
    // End of variables declaration//GEN-END:variables
}
